"""Generate Figure 8a and 8e: exemplar aligned latent trajectories."""

import os
import pickle

import matplotlib.pyplot as plt

from affective_task.utils import Constants, save_figure
from affective_task.visualization import PlotModelLatents


class Figure8AE:
    """Plot two exemplar sets of aligned repeat/switch latent trajectories."""

    analysis_dir = "model_analysis"
    stats_fn = "holdout_outputs_01SD.pkl"

    # Subject-specific rotation matrices generated by Figure 3a.
    patient_rs = "../../dataset/patient_rs.pkl"

    # Exemplar participants.
    A_id = "66_1"
    B_id = "34"

    figsize = (10, 4)
    figdpi = 300

    def __init__(self, model_dir, save_dir, patients_id, rand_seed, n_boot):
        self.model_dir = model_dir
        self.save_dir = save_dir
        self.patients_id = patients_id

        # Retain the common figure-class constructor signature.
        _ = rand_seed
        _ = n_boot

        self.A_stats = None
        self.B_stats = None

    def make_figure(self):
        """Generate and save Figure 8a/e."""
        print("Making Figure 8ae...")
        self._run_preprocessing()

        print("Stats for Figure 8ae")
        print("--------------------")

        fig = self._plot_figure_get_stats()
        save_figure(
            fig,
            self.save_dir,
            "Fig8ae",
        )
        return fig

    def _run_preprocessing(self):
        """Load the two exemplar model outputs and rotation matrices."""
        exemplar_ids = {
            self.A_id,
            self.B_id,
        }

        for patient_id in self.patients_id:
            if patient_id not in exemplar_ids:
                continue

            stats_path = os.path.join(
                self.model_dir,
                "s{}".format(patient_id),
                self.analysis_dir,
                self.stats_fn,
            )
            with open(stats_path, "rb") as path:
                expt_stats = pickle.load(path)

            if patient_id == self.A_id:
                self.A_stats = expt_stats
            elif patient_id == self.B_id:
                self.B_stats = expt_stats

        with open(self.patient_rs, "rb") as path:
            self.group_Rs = pickle.load(path)

        print(
            "Data successfully loaded from {}".format(
                self.patient_rs
            )
        )

    def _plot_figure_get_stats(self):
        """Assemble the two exemplar trajectory panels."""
        fig = plt.figure(
            constrained_layout=False,
            figsize=self.figsize,
            dpi=self.figdpi,
        )
        gs = fig.add_gridspec(7, 15)

        # ------------------------------------------------------------------
        # Figure 8a: exemplar participant 66_1.
        # ------------------------------------------------------------------
        ax_a = fig.add_subplot(
            gs[0:7, 0:7],
            projection="3d",
        )
        plot_kwargs_a = {
            "xlim": [-5, 15],
            "ylim": [-13, 5],
            "zlim": [0, 18],
            "colors": [
                          Constants.COLOR_G2G,
                          Constants.COLOR_E2E,
                          Constants.COLOR_E2G,
                          Constants.COLOR_G2E,
                      ] * 2,
            "line_styles": ["-"] * 4 + ["--"] * 4,
            "annotate": "global",
            "plot_t_posts": [
                1000,
                1000,
                1000,
                1200,
                1200,
                1200,
                1200,
                1200,
            ],
            "R": self.group_Rs[self.A_id],
        }
        self._make_full_condition_panel(
            ax=ax_a,
            stats=self.A_stats,
            plot_kwargs=plot_kwargs_a,
            azim=85,
        )

        # ------------------------------------------------------------------
        # Figure 8e: exemplar participant 34.
        # ------------------------------------------------------------------
        ax_b = fig.add_subplot(
            gs[0:7, 8:15],
            projection="3d",
        )
        plot_kwargs_b = {
            "xlim": [-5, 17],
            "ylim": [-14, -2],
            "zlim": [-10, 5],
            "colors": [
                          Constants.COLOR_G2G,
                          Constants.COLOR_E2E,
                          Constants.COLOR_E2G,
                          Constants.COLOR_G2E,
                      ] * 2,
            "line_styles": ["-"] * 4 + ["--"] * 4,
            "annotate": "global",
            "plot_t_posts": [
                1100,
                1100,
                1100,
                1100,
                1100,
                1100,
                1100,
                1300,
            ],
            "R": self.group_Rs[self.B_id],
        }
        self._make_full_condition_panel(
            ax=ax_b,
            stats=self.B_stats,
            plot_kwargs=plot_kwargs_b,
            azim=70,
        )

        return fig

    @staticmethod
    def _make_full_condition_panel(
            ax,
            stats,
            plot_kwargs,
            elev=40,
            azim=60,
            t_post=1400,
    ):
        """Plot all repeat and switch conditions for one exemplar participant."""
        plotter = PlotModelLatents(
            stats,
            post_on_dur=t_post,
            plot_pre_onset=False,
        )
        plotter.plot_full_conditions(
            ax,
            elev=elev,
            azim=azim,
            plot_task_centroid=False,
            **plot_kwargs
        )
