"""Generate Figure 8b and 8f: task-relevant and task-irrelevant alignment."""

import os
import pickle
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.stats import (
    PearsonRConstantInputWarning,
    sem,
    ttest_1samp,
    ttest_rel,
)

from affective_task.utils import (
    Constants,
    compute_subject_theta_repeat,
    compute_subject_theta_switch,
    p_to_stars,
    save_figure,
)


class Figure8BF:
    """Plot repeat-task relevant and switch-task irrelevant alignment."""

    analysis_dir = "model_analysis"
    stats_fn = "holdout_outputs_01SD.pkl"

    # Subject-specific rotation matrices generated by Figure 3a.
    patient_rs = "../../dataset/patient_rs.pkl"

    # HDDM non-decision times used by the theta-analysis utilities.
    dataset_path = "../../dataset/"
    hddm_stats_fn = "HDDM_group_results_vat_all-trials.csv"

    figsize = (9, 4)
    figdpi = 300

    def __init__(self, model_dir, save_dir, patients_id, rand_seed, n_boot):
        self.model_dir = model_dir
        self.save_dir = save_dir
        self.patients_id = patients_id

        # Retain the common figure-class constructor signature.
        _ = rand_seed
        _ = n_boot

        warnings.simplefilter(
            "ignore",
            PearsonRConstantInputWarning,
        )

        self.hddm_stats = pd.read_csv(
            os.path.join(
                self.dataset_path,
                self.hddm_stats_fn,
            ),
            index_col=0,
        )

        self.subject_experiments = {}

    def make_figure(self):
        """Generate and save Figure 8b and 8f."""
        print("Making Figure 8bf...")
        self._run_preprocessing()

        print("Stats for Figure 8bf")
        print("--------------------")

        fig = self._plot_figure_get_stats()
        save_figure(
            fig,
            self.save_dir,
            "Fig8bf",
        )
        return fig

    def _run_preprocessing(self):
        """Load participant model outputs and semantic-axis rotations."""
        for patient_id in self.patients_id:
            stats_path = os.path.join(
                self.model_dir,
                "s{}".format(patient_id),
                self.analysis_dir,
                self.stats_fn,
            )
            with open(stats_path, "rb") as path:
                self.subject_experiments[patient_id] = pickle.load(path)

        with open(self.patient_rs, "rb") as path:
            self.group_Rs = pickle.load(path)

        print(
            "Data successfully loaded from {}".format(
                self.patient_rs
            )
        )

    def _plot_figure_get_stats(self):
        """Assemble Figure 8b and 8f and print their statistics."""
        fig = plt.figure(
            constrained_layout=False,
            figsize=self.figsize,
            dpi=self.figdpi,
        )
        gs = fig.add_gridspec(5, 12)

        # ------------------------------------------------------------------
        # Figure 8f: task-relevant alignment for repeat trials over [NDT, RT].
        # ------------------------------------------------------------------
        repeat_df = self._compute_repeat_alignment_dataframe(
            t_start=Constants.T_NDT,
            t_end=Constants.T_RT,
        )

        ax_repeat = fig.add_subplot(
            gs[0:5, 0:5]
        )
        self._make_paired_alignment_panel(
            ax=ax_repeat,
            df=repeat_df,
            order=["G2G", "E2E"],
            palette=[
                Constants.COLOR_G2G,
                Constants.COLOR_E2E,
            ],
            title=r"$A_{rel}$ - [NDT, RT]",
            ylabel=r"$A_{rel}$ - [NDT, RT]",
            range_ylim=(-0.05, 1.15),
        )

        # ------------------------------------------------------------------
        # Figure 8b: task-irrelevant alignment for switch trials over [0, NDT].
        # ------------------------------------------------------------------
        switch_df = self._compute_switch_alignment_dataframe(
            t_start=Constants.T_START,
            t_end=Constants.T_NDT,
        )

        ax_switch = fig.add_subplot(
            gs[0:5, 7:12]
        )
        self._make_paired_alignment_panel(
            ax=ax_switch,
            df=switch_df,
            order=["E2G", "G2E"],
            palette=[
                Constants.COLOR_E2G,
                Constants.COLOR_G2E,
            ],
            title=r"$A_{irr}$ - [0, NDT]",
            ylabel=r"$A_{irr}$ - [0, NDT]",
            range_ylim=(-0.05, 1.15),
        )

        return fig

    def _get_subject_hddm_ndt(self, patient_id):
        """Return the participant's HDDM non-decision-time rows."""
        return self.hddm_stats.loc[
            (self.hddm_stats["subj_id"] == str(patient_id))
            & (self.hddm_stats["param"] == "non decision time")
            ]

    def _compute_repeat_alignment_dataframe(
            self,
            t_start,
            t_end,
            coord_cols=("x", "y", "z"),
            t_col="t",
            grid_n=100,
    ):
        """Compute repeat-trial task-relevant alignment for each participant."""
        rows = []

        for patient_id in self.patients_id:
            experiment = self.subject_experiments[
                patient_id
            ]
            patient_rotation = self.group_Rs[
                patient_id
            ]
            ndt_df = self._get_subject_hddm_ndt(
                patient_id
            )

            theta = compute_subject_theta_repeat(
                experiment,
                patient_rotation,
                coord_cols=coord_cols,
                t_col=t_col,
                grid_n=grid_n,
                t_start=t_start,
                t_end=t_end,
                ndt_df=ndt_df,
            )

            # Task-relevant alignment:
            #   G2G -> emotion contrast within each gender.
            #   E2E -> gender contrast within each emotion.
            g2g_alignment = (
                                    theta["theta_m_e_g2g"]
                                    + theta["theta_f_e_g2g"]
                            ) / 2.0
            e2e_alignment = (
                                    theta["theta_g_h_e2e"]
                                    + theta["theta_g_a_e2e"]
                            ) / 2.0

            rows.append(
                {
                    "subj": patient_id,
                    "G2G": g2g_alignment,
                    "E2E": e2e_alignment,
                }
            )

        return pd.DataFrame(
            rows
        )

    def _compute_switch_alignment_dataframe(
            self,
            t_start,
            t_end,
            coord_cols=("x", "y", "z"),
            t_col="t",
            grid_n=100,
    ):
        """Compute switch-trial task-irrelevant alignment for each participant."""
        rows = []

        for patient_id in self.patients_id:
            experiment = self.subject_experiments[
                patient_id
            ]
            patient_rotation = self.group_Rs[
                patient_id
            ]
            ndt_df = self._get_subject_hddm_ndt(
                patient_id
            )

            theta = compute_subject_theta_switch(
                experiment,
                patient_rotation,
                coord_cols=coord_cols,
                t_col=t_col,
                grid_n=grid_n,
                t_start=t_start,
                t_end=t_end,
                ndt_df=ndt_df,
            )

            # Task-irrelevant alignment:
            #   E2G -> gender contrast while switching to gender.
            #   G2E -> emotion contrast while switching to emotion.
            e2g_alignment = (
                                    theta["theta_g_h_e2g"]
                                    + theta["theta_g_a_e2g"]
                            ) / 2.0
            g2e_alignment = (
                                    theta["theta_m_e_g2e"]
                                    + theta["theta_f_e_g2e"]
                            ) / 2.0

            rows.append(
                {
                    "subj": patient_id,
                    "E2G": e2g_alignment,
                    "G2E": g2e_alignment,
                }
            )

        return pd.DataFrame(
            rows
        )

    def _make_paired_alignment_panel(
            self,
            ax,
            df,
            order,
            palette,
            title,
            ylabel,
            range_ylim=None,
            connect_lines=True,
    ):
        """Plot two paired alignment conditions with one-sample and paired tests."""
        required_columns = [
                               "subj"
                           ] + list(order)
        missing = [
            column
            for column in required_columns
            if column not in df.columns
        ]
        if missing:
            raise ValueError(
                "Missing required columns: {}".format(
                    missing
                )
            )

        long_df = df[
            required_columns
        ].melt(
            id_vars="subj",
            var_name="condition",
            value_name="value",
        )
        long_df["condition"] = pd.Categorical(
            long_df["condition"],
            categories=order,
            ordered=True,
        )

        print(title)
        print("One-sample t-tests against zero:")

        for condition in order:
            values = long_df.loc[
                long_df["condition"] == condition,
                "value",
            ].dropna().to_numpy(
                dtype=float
            )

            t_stat, p_value = ttest_1samp(
                values,
                0.0,
                nan_policy="omit",
            )

            print(
                "{}: one-sample t-test vs. 0, "
                "t({}) = {:.3f}, p = {:.4g}, N = {}, "
                "mean +/- s.e.m. = {:.4f} +/- {:.4f}".format(
                    condition,
                    len(values) - 1,
                    t_stat,
                    p_value,
                    len(values),
                    np.mean(values),
                    sem(
                        values,
                        nan_policy="omit",
                    ),
                )
            )

        sns.boxplot(
            data=long_df,
            x="condition",
            y="value",
            order=order,
            palette=palette,
            showcaps=True,
            fliersize=0,
            width=0.7,
            linewidth=0.8,
            ax=ax,
        )
        sns.stripplot(
            data=long_df,
            x="condition",
            y="value",
            order=order,
            palette=palette,
            size=4,
            alpha=0.75,
            jitter=False,
            edgecolor="black",
            linewidth=0.2,
            zorder=10,
            ax=ax,
        )

        wide = long_df.pivot_table(
            index="subj",
            columns="condition",
            values="value",
            aggfunc="mean",
        )

        if connect_lines:
            x_positions = {
                condition: i
                for i, condition in enumerate(order)
            }

            for _, row in wide.iterrows():
                values = row.reindex(
                    order
                ).to_numpy(
                    dtype=float
                )
                if np.any(
                        np.isnan(values)
                ):
                    continue

                ax.plot(
                    [
                        x_positions[condition]
                        for condition in order
                    ],
                    values,
                    color="gray",
                    alpha=0.55,
                    lw=0.8,
                    zorder=2,
                )

        if range_ylim is not None:
            ax.set_ylim(
                range_ylim
            )

        paired = wide[
            order
        ].dropna()

        first_values = paired[
            order[0]
        ].to_numpy(
            dtype=float
        )
        second_values = paired[
            order[1]
        ].to_numpy(
            dtype=float
        )

        t_stat, p_value = ttest_rel(
            first_values,
            second_values,
            nan_policy="omit",
        )
        difference = (
                first_values
                - second_values
        )
        significance = p_to_stars(
            p_value
        )

        print("Paired t-test:")
        print(
            "{} vs {}: paired t-test, "
            "t({}) = {:.3f}, p = {:.4g}, N = {}, "
            "mean paired difference ({} - {}) +/- s.e.m. = "
            "{:.4f} +/- {:.4f} ({})".format(
                order[0],
                order[1],
                len(paired) - 1,
                t_stat,
                p_value,
                len(paired),
                order[0],
                order[1],
                np.mean(
                    difference
                ),
                sem(
                    difference,
                    nan_policy="omit",
                ),
                significance,
            )
        )

        # Preserve the original bracket placement relative to the current
        # axis range.
        y_max_data = float(
            np.nanmax(
                long_df["value"].to_numpy(
                    dtype=float
                )
            )
        )
        y_min_axis, y_max_axis = ax.get_ylim()
        y_range = (
            float(
                y_max_axis
                - y_min_axis
            )
            if (
                       y_max_axis
                       - y_min_axis
               ) > 0
            else max(
                1.0,
                abs(
                    y_max_data
                ),
            )
        )

        bracket_y = (
                y_max_data
                + 0.08 * y_range
        )
        bracket_height = (
                0.015 * y_range
        )

        self._add_bracket(
            ax,
            0,
            1,
            bracket_y,
            bracket_height,
            significance,
            fontsize=6,
        )

        ax.set_title(
            title,
            fontsize=4,
        )
        ax.set_xlabel(
            "Trial types"
        )
        ax.set_ylabel(
            ylabel
        )

        if ax.legend_:
            ax.legend_.remove()

        ax.set_xticklabels(
            order,
            fontsize=9,
        )

        if range_ylim is not None:
            ax.set_ylim(
                range_ylim
            )
        else:
            top_y = (
                    bracket_y
                    + bracket_height
                    + 0.06 * y_range
            )
            ax.set_ylim(
                y_min_axis,
                max(
                    y_max_axis,
                    top_y,
                ),
            )

    @staticmethod
    def _add_bracket(
            ax,
            x1,
            x2,
            y,
            h,
            text,
            fontsize=12,
    ):
        """Draw a significance bracket between two conditions."""
        ax.plot(
            [x1, x1, x2, x2],
            [y, y + h, y + h, y],
            color="black",
            lw=1.2,
        )
        ax.text(
            (x1 + x2) / 2.0,
            y + h,
            text,
            ha="center",
            va="bottom",
            fontsize=fontsize,
            fontweight="bold",
        )
