"""Generate Figure 8c-d: switch-trial irrelevant alignment vs. HDDM t0."""

import os
import pickle
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import PearsonRConstantInputWarning, pearsonr
from statsmodels.stats.multitest import multipletests

from affective_task.utils import (
    Constants,
    compute_subject_theta_switch,
    save_figure,
)


class Figure8CD:
    """Plot early task-irrelevant alignment against HDDM non-decision time."""

    analysis_dir = "model_analysis"
    stats_fn = "holdout_outputs_01SD.pkl"

    # Subject-specific rotation matrices generated by Figure 3a.
    patient_rs = "../../dataset/patient_rs.pkl"

    # Hierarchical drift-diffusion model parameters.
    dataset_path = "../../dataset/"
    hddm_stats_fn = "HDDM_group_results_vat_all-trials.csv"

    figsize = (9, 3)
    figdpi = 300

    def __init__(self, model_dir, save_dir, patients_id, rand_seed, n_boot):
        self.model_dir = model_dir
        self.save_dir = save_dir
        self.patients_id = patients_id

        # Retain the common figure-class constructor signature.
        _ = rand_seed
        _ = n_boot

        warnings.simplefilter(
            "ignore",
            PearsonRConstantInputWarning,
        )

        self.hddm_stats = pd.read_csv(
            os.path.join(
                self.dataset_path,
                self.hddm_stats_fn,
            ),
            index_col=0,
        )
        self.subject_experiments = {}

    def make_figure(self):
        """Generate and save Figure 8c-d."""
        print("Making Figure 8cd...")
        self._run_preprocessing()

        print("Stats for Figure 8cd")
        print("--------------------")

        fig = self._plot_figure_get_stats()
        save_figure(
            fig,
            self.save_dir,
            "Fig8cd",
        )
        return fig

    def _run_preprocessing(self):
        """Load participant model outputs and semantic-axis rotations."""
        for patient_id in self.patients_id:
            stats_path = os.path.join(
                self.model_dir,
                "s{}".format(patient_id),
                self.analysis_dir,
                self.stats_fn,
            )
            with open(stats_path, "rb") as path:
                self.subject_experiments[patient_id] = pickle.load(path)

        with open(self.patient_rs, "rb") as path:
            self.group_Rs = pickle.load(path)

        print(
            "Data successfully loaded from {}".format(
                self.patient_rs
            )
        )

    def _plot_figure_get_stats(self):
        """Assemble Figure 8c-d and print the associated statistics."""
        fig = plt.figure(
            constrained_layout=False,
            figsize=self.figsize,
            dpi=self.figdpi,
        )
        gs = fig.add_gridspec(5, 12)

        df = self._compute_switch_irrelevant_alignment_dataframe(
            t_start=Constants.T_START,
            t_end=Constants.T_NDT,
        )

        ax_e2g = fig.add_subplot(
            gs[0:5, 0:5]
        )
        stats_e2g = self._plot_alignment_vs_t0(
            ax=ax_e2g,
            df=df,
            x_col="cs_e2g",
            y_col="nt_e2g",
            xlabel=(
                r"$CS_{irr}$-[0, NDT] for e2g. "
                r"$\left(\bar{c}_{\mathrm{male\!-\!happy},\,"
                r"\mathrm{male\!-\!angry}}^{e2g} + "
                r"\bar{c}_{\mathrm{female\!-\!happy},\,"
                r"\mathrm{female\!-\!angry}}^{e2g}\right) / 2$"
            ),
            ylabel="non-decision time for e2g",
            range_xlim=(0.38, 0.96),
            range_ylim=(0.45, 1.4),
            seed=0,
        )

        ax_g2e = fig.add_subplot(
            gs[0:5, 7:12]
        )
        stats_g2e = self._plot_alignment_vs_t0(
            ax=ax_g2e,
            df=df,
            x_col="cs_g2e",
            y_col="nt_g2e",
            xlabel=(
                r"$CS_{irr}$-[0, NDT] for g2e, "
                r"$\left(\bar{c}_{\mathrm{male\!-\!happy},\,"
                r"\mathrm{female\!-\!happy}}^{g2e} + "
                r"\bar{c}_{\mathrm{male\!-\!angry},\,"
                r"\mathrm{female\!-\!angry}}^{g2e}\right) / 2$"
            ),
            ylabel="non-decision time for g2e",
            range_xlim=(0.38, 0.96),
            range_ylim=(0.45, 1.4),
            seed=0,
        )

        # Planned correction family: the two Fig. 8c-d permutation tests.
        conditions = ["G2E", "E2G"]
        raw_pvalues = [
            stats_g2e["perm_p"],
            stats_e2g["perm_p"],
        ]
        reject, adjusted_pvalues, _, _ = multipletests(
            raw_pvalues,
            alpha=0.05,
            method="holm",
        )

        for (
                condition,
                raw_p,
                adjusted_p,
                significant,
        ) in zip(
            conditions,
            raw_pvalues,
            adjusted_pvalues,
            reject,
        ):
            print(
                "{} raw p = {} Holm p = {} significant = {}".format(
                    condition,
                    raw_p,
                    adjusted_p,
                    significant,
                )
            )

        return fig

    def _compute_switch_irrelevant_alignment_dataframe(
            self,
            t_start,
            t_end,
            coord_cols=("x", "y", "z"),
            t_col="t",
            grid_n=100,
    ):
        """Compute E2G/G2E early task-irrelevant alignment for each subject."""
        rows = []

        for patient_id in self.patients_id:
            experiment = self.subject_experiments[
                patient_id
            ]
            patient_rotation = self.group_Rs[
                patient_id
            ]
            ndt_df = self._get_subject_hddm_ndt(
                patient_id
            )

            theta = compute_subject_theta_switch(
                experiment,
                patient_rotation,
                coord_cols=coord_cols,
                t_col=t_col,
                grid_n=grid_n,
                t_start=t_start,
                t_end=t_end,
                ndt_df=ndt_df,
            )

            # Preserve the original Fig. 8c-d task-irrelevant definitions.
            cs_e2g = (
                             theta["theta_g_h_e2g"]
                             + theta["theta_g_a_e2g"]
                     ) / 2.0
            cs_g2e = (
                             theta["theta_m_e_g2e"]
                             + theta["theta_f_e_g2e"]
                     ) / 2.0

            rows.append(
                {
                    "subj": patient_id,
                    "cs_e2g": cs_e2g,
                    "cs_g2e": cs_g2e,
                    "nt_e2g": self._get_hddm_trial_value(
                        ndt_df,
                        "Gender Switch Trials",
                    ),
                    "nt_g2e": self._get_hddm_trial_value(
                        ndt_df,
                        "Emotion Switch Trials",
                    ),
                }
            )

        return pd.DataFrame(
            rows
        )

    def _get_subject_hddm_ndt(self, patient_id):
        """Return HDDM non-decision-time rows for one participant."""
        return self.hddm_stats.loc[
            (self.hddm_stats["subj_id"] == str(patient_id))
            & (self.hddm_stats["param"] == "non decision time")
            ]

    @staticmethod
    def _get_hddm_trial_value(ndt_df, trial_label):
        """Return the HDDM posterior mean for one trial type."""
        return float(
            ndt_df.loc[
                ndt_df["trial"] == trial_label,
                "mean",
            ].iloc[0]
        )

    def _plot_alignment_vs_t0(
            self,
            ax,
            df,
            x_col,
            y_col,
            xlabel,
            ylabel,
            n_boot=10000,
            n_perm=10000,
            ci=95,
            seed=0,
            range_xlim=None,
            range_ylim=None,
    ):
        """Plot Pearson association with bootstrap CI and permutation p-value."""
        x = df[
            x_col
        ].to_numpy(
            dtype=float
        )
        y = df[
            y_col
        ].to_numpy(
            dtype=float
        )

        valid = (
                np.isfinite(x)
                & np.isfinite(y)
        )
        x = x[valid]
        y = y[valid]

        n = len(x)
        if n < 3:
            raise ValueError(
                "Not enough valid observations for {} vs. {}.".format(
                    x_col,
                    y_col,
                )
            )

        r_observed, _ = pearsonr(
            x,
            y,
        )
        ci_low, ci_high = self._bootstrap_corr_ci(
            x,
            y,
            n_boot=n_boot,
            ci=ci,
            seed=seed,
        )

        x_pad = 0.05 * (
                np.max(x)
                - np.min(x)
                + 1e-12
        )
        x_grid = np.linspace(
            np.min(x) - x_pad,
            np.max(x) + x_pad,
            200,
        )
        y_hat, y_low, y_high = (
            self._bootstrap_regression_band(
                x,
                y,
                x_grid,
                n_boot=n_boot,
                ci=ci,
                seed=seed,
            )
        )

        perm_p = self._permutation_pvalue(
            x,
            y,
            r_observed,
            n_perm=n_perm,
            seed=seed,
        )

        ax.scatter(
            x,
            y,
            alpha=0.9,
            s=4,
            color="#377EB8",
        )
        ax.plot(
            x_grid,
            y_hat,
            linewidth=1,
            color="#E64B35",
        )
        ax.fill_between(
            x_grid,
            y_low,
            y_high,
            alpha=0.2,
            color="gray",
        )

        annotation = (
            "Pearson r = {:.3f}\n"
            "{}% bootstrap CI [{:.3f}, {:.3f}]\n"
            "perm p = {:.4f}\n"
            "n = {}".format(
                r_observed,
                int(ci),
                ci_low,
                ci_high,
                perm_p,
                n,
            )
        )
        ax.text(
            0.02,
            0.98,
            annotation,
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=4,
        )

        ax.set_xlabel(
            xlabel
        )
        ax.set_ylabel(
            ylabel
        )

        if range_xlim is not None:
            ax.set_xlim(
                range_xlim
            )
        if range_ylim is not None:
            ax.set_ylim(
                range_ylim
            )

        return {
            "n_used": n,
            "r_obs": float(
                r_observed
            ),
            "ci_low": float(
                ci_low
            ),
            "ci_high": float(
                ci_high
            ),
            "perm_p": float(
                perm_p
            ),
        }

    @staticmethod
    def _ols_slope_intercept(x, y):
        """Return slope and intercept for y = intercept + slope * x."""
        x = np.asarray(
            x,
            dtype=float,
        )
        y = np.asarray(
            y,
            dtype=float,
        )

        x_mean = np.mean(
            x
        )
        y_mean = np.mean(
            y
        )
        denominator = np.sum(
            (
                    x
                    - x_mean
            ) ** 2
        )

        if denominator <= 1e-12:
            return np.nan, np.nan

        slope = np.sum(
            (
                    x
                    - x_mean
            )
            * (
                    y
                    - y_mean
            )
        ) / denominator
        intercept = (
                y_mean
                - slope * x_mean
        )

        return float(
            slope
        ), float(
            intercept
        )

    def _bootstrap_regression_band(
            self,
            x,
            y,
            x_grid,
            n_boot=10000,
            ci=95,
            seed=0,
    ):
        """Bootstrap the pointwise CI band for the OLS regression line."""
        rng = np.random.RandomState(
            seed
        )

        x = np.asarray(
            x,
            dtype=float,
        )
        y = np.asarray(
            y,
            dtype=float,
        )
        valid = (
                np.isfinite(x)
                & np.isfinite(y)
        )
        x = x[valid]
        y = y[valid]

        slope, intercept = self._ols_slope_intercept(
            x,
            y,
        )
        y_hat = (
                intercept
                + slope * x_grid
        )

        predictions = np.zeros(
            (
                int(n_boot),
                len(x_grid),
            ),
            dtype=float,
        )

        n_samples = len(x)
        for i in range(
                int(n_boot)
        ):
            indices = rng.randint(
                0,
                n_samples,
                size=n_samples,
            )
            slope_i, intercept_i = self._ols_slope_intercept(
                x[indices],
                y[indices],
            )
            predictions[i, :] = (
                    intercept_i
                    + slope_i * x_grid
            )

        alpha = (
                        100.0 - ci
                ) / 2.0
        y_low = np.percentile(
            predictions,
            alpha,
            axis=0,
        )
        y_high = np.percentile(
            predictions,
            100.0 - alpha,
            axis=0,
        )

        return y_hat, y_low, y_high

    @staticmethod
    def _bootstrap_corr_ci(
            x,
            y,
            n_boot=10000,
            ci=95,
            seed=0,
    ):
        """Bootstrap a confidence interval for Pearson's correlation."""
        rng = np.random.RandomState(
            seed
        )
        n_samples = len(x)

        boot_rs = np.zeros(
            int(n_boot),
            dtype=float,
        )

        for i in range(
                int(n_boot)
        ):
            indices = rng.randint(
                0,
                n_samples,
                size=n_samples,
            )
            r_boot, _ = pearsonr(
                x[indices],
                y[indices],
            )
            boot_rs[i] = r_boot

        alpha = (
                        100.0 - ci
                ) / 2.0
        ci_low = np.percentile(
            boot_rs,
            alpha,
        )
        ci_high = np.percentile(
            boot_rs,
            100.0 - alpha,
        )

        return float(
            ci_low
        ), float(
            ci_high
        )

    @staticmethod
    def _permutation_pvalue(
            x,
            y,
            r_observed,
            n_perm=10000,
            seed=0,
    ):
        """Return a two-sided permutation p-value for Pearson's r."""
        rng = np.random.RandomState(
            seed
        )
        n_samples = len(y)

        permuted_rs = np.zeros(
            int(n_perm),
            dtype=float,
        )

        for i in range(
                int(n_perm)
        ):
            y_shuffled = y[
                rng.permutation(
                    n_samples
                )
            ]
            permuted_rs[i] = pearsonr(
                x,
                y_shuffled,
            )[0]

        return float(
            (
                    np.sum(
                        np.abs(
                            permuted_rs
                        )
                        >= abs(
                            r_observed
                        )
                    )
                    + 1.0
            )
            / (
                    len(
                        permuted_rs
                    )
                    + 1.0
            )
        )
