"""Generate Figure 4: exemplar repeat and switch latent trajectories."""

import os
import pickle

import matplotlib.pyplot as plt

from affective_task.utils import Constants, save_figure
from affective_task.visualization import PlotModelLatents


class Figure4:
    """Plot exemplar latent trajectories in the aligned UMAP space."""

    analysis_dir = "model_analysis"
    stats_fn = "holdout_outputs_01SD.pkl"

    # Subject-specific rotation matrices generated by Figure 3a.
    patient_rs = "../../dataset/patient_rs.pkl"

    # Exemplar participants.
    repeat_exemplar_1 = "25"
    repeat_exemplar_2 = "27"
    switch_exemplar_1 = "36"
    switch_exemplar_2 = "37"

    figsize = (10, 10)
    figdpi = 300
    T_POST = 1600

    def __init__(self, model_dir, save_dir, patients_id, rand_seed, n_boot):
        self.model_dir = model_dir
        self.save_dir = save_dir
        self.patients_id = patients_id

        # Retain the common figure-class constructor signature.
        _ = rand_seed
        _ = n_boot

        self.exemplar_stats = {}

    def make_figure(self):
        """Generate and save Figure 4."""
        print("Making Figure 4...")
        self._run_preprocessing()

        print("Stats for Figure 4")
        print("------------------")

        fig = self._plot_figure_get_stats()
        save_figure(fig, self.save_dir, "Fig4")
        return fig

    def _run_preprocessing(self):
        """Load exemplar model outputs and subject rotation matrices."""
        exemplar_ids = {
            self.repeat_exemplar_1,
            self.repeat_exemplar_2,
            self.switch_exemplar_1,
            self.switch_exemplar_2,
        }

        for patient_id in self.patients_id:
            if patient_id not in exemplar_ids:
                continue

            stats_path = os.path.join(
                self.model_dir,
                "s{}".format(patient_id),
                self.analysis_dir,
                self.stats_fn,
            )
            with open(stats_path, "rb") as path:
                self.exemplar_stats[patient_id] = pickle.load(path)

        with open(self.patient_rs, "rb") as path:
            self.group_Rs = pickle.load(path)

        print(
            "Data successfully loaded from {}".format(
                self.patient_rs
            )
        )

    def _plot_figure_get_stats(self):
        """Assemble the four exemplar trajectory panels."""
        fig = plt.figure(
            constrained_layout=False,
            figsize=self.figsize,
            dpi=self.figdpi,
        )
        gs = fig.add_gridspec(15, 15)

        # ------------------------------------------------------------------
        # Top row: all repeat/switch trajectories for two exemplar subjects.
        # ------------------------------------------------------------------
        ax_a = fig.add_subplot(
            gs[0:7, 0:7],
            projection="3d",
        )
        plot_kwargs_a = {
            "xlim": [-4, 14],
            "ylim": [-4, 14],
            "zlim": [-4, 14],
            "colors": [
                          Constants.COLOR_G2G,
                          Constants.COLOR_E2E,
                          Constants.COLOR_E2G,
                          Constants.COLOR_G2E,
                      ]
                      * 2,
            "line_styles": ["-"] * 4 + ["--"] * 4,
            "annotate": "global",
            "R": self.group_Rs[self.repeat_exemplar_1],
        }
        self._make_full_condition_panel(
            ax_a,
            self.exemplar_stats[self.repeat_exemplar_1],
            plot_kwargs_a,
        )

        ax_b = fig.add_subplot(
            gs[0:7, 8:15],
            projection="3d",
        )
        plot_kwargs_b = {
            "xlim": [-6, 16],
            "ylim": [-9, 6],
            "zlim": [-20, 1],
            "colors": [
                          Constants.COLOR_G2G,
                          Constants.COLOR_E2E,
                          Constants.COLOR_E2G,
                          Constants.COLOR_G2E,
                      ]
                      * 2,
            "line_styles": ["-"] * 4 + ["--"] * 4,
            "annotate": "global",
            "plot_t_posts": [1300] * 8,
            "R": self.group_Rs[self.repeat_exemplar_2],
        }
        self._make_full_condition_panel(
            ax_b,
            self.exemplar_stats[self.repeat_exemplar_2],
            plot_kwargs_b,
        )

        # ------------------------------------------------------------------
        # Bottom row: female-happy repeat/switch trajectories.
        # ------------------------------------------------------------------
        ax_c = fig.add_subplot(
            gs[8:15, 0:7],
            projection="3d",
        )
        plot_kwargs_c = {
            "xlim": [-15, 10],
            "ylim": [-7, 10],
            "zlim": [-1, 13],
            "annotate": "global",
            "R": self.group_Rs[self.switch_exemplar_1],
        }
        self._make_female_happy_panel(
            ax_c,
            self.exemplar_stats[self.switch_exemplar_1],
            elev=80,
            azim=-260,
            plot_kwargs=plot_kwargs_c,
            plot_t_posts={
                "G2G": 1000,
                "E2G": 1300,
                "E2E": 1000,
                "G2E": 1600,
            },
        )

        ax_d = fig.add_subplot(
            gs[8:15, 8:15],
            projection="3d",
        )
        plot_kwargs_d = {
            "xlim": [-7, 12],
            "ylim": [-3, 21],
            "zlim": [-17, 2],
            "annotate": "global",
            "R": self.group_Rs[self.switch_exemplar_2],
        }
        self._make_female_happy_panel(
            ax_d,
            self.exemplar_stats[self.switch_exemplar_2],
            elev=80,
            azim=120,
            plot_kwargs=plot_kwargs_d,
            plot_t_posts={
                "G2G": 1200,
                "E2G": 1200,
                "E2E": 1000,
                "G2E": 1400,
            },
        )

        return fig

    @staticmethod
    def _make_full_condition_panel(
            ax,
            stats,
            plot_kwargs,
            elev=40,
            azim=60,
            t_post=1400,
    ):
        """Plot all repeat/switch conditions for one exemplar participant."""
        plotter = PlotModelLatents(
            stats,
            post_on_dur=t_post,
            plot_pre_onset=False,
        )
        plotter.plot_full_conditions(
            ax,
            elev=elev,
            azim=azim,
            plot_task_centroid=False,
            **plot_kwargs
        )

    def _make_female_happy_panel(
            self,
            ax,
            stats,
            elev,
            azim,
            plot_kwargs,
            plot_t_posts,
            t_post=T_POST,
    ):
        """Plot G2G/E2G and E2E/G2E female-happy trajectories."""
        plotter = PlotModelLatents(
            stats,
            post_on_dur=t_post,
            plot_pre_onset=False,
        )

        self._plot_single_condition(
            plotter,
            plotter.plot_g2g_female_happy,
            ax,
            elev,
            azim,
            plot_kwargs,
            color=Constants.COLOR_G2G,
            line_style="-",
            plot_t_post=plot_t_posts["G2G"],
        )
        self._plot_single_condition(
            plotter,
            plotter.plot_e2g_female_happy,
            ax,
            elev,
            azim,
            plot_kwargs,
            color=Constants.COLOR_G2G,
            line_style="--",
            plot_t_post=plot_t_posts["E2G"],
        )
        self._plot_single_condition(
            plotter,
            plotter.plot_e2e_female_happy,
            ax,
            elev,
            azim,
            plot_kwargs,
            color=Constants.COLOR_E2E,
            line_style="-",
            plot_t_post=plot_t_posts["E2E"],
        )
        self._plot_single_condition(
            plotter,
            plotter.plot_g2e_female_happy,
            ax,
            elev,
            azim,
            plot_kwargs,
            color=Constants.COLOR_E2E,
            line_style="--",
            plot_t_post=plot_t_posts["G2E"],
        )

    @staticmethod
    def _plot_single_condition(
            plotter,
            plot_function,
            ax,
            elev,
            azim,
            plot_kwargs,
            color,
            line_style,
            plot_t_post,
    ):
        """Plot one trajectory while preserving the panel's shared settings."""
        kwargs = dict(plot_kwargs)
        kwargs["plot_t_posts"] = [plot_t_post]
        kwargs["line_styles"] = [line_style]
        kwargs["colors"] = [color]

        plot_function(
            ax,
            elev=elev,
            azim=azim,
            plot_task_centroid=False,
            **kwargs
        )
