"""Generate Figure 6a: exemplar emotion-task repeat and switch trajectories."""

import os
import pickle

import matplotlib.pyplot as plt

from affective_task.utils import Constants, save_figure
from affective_task.visualization import PlotModelLatents


class Figure6A:
    """Plot exemplar E2E and G2E trajectories in the aligned UMAP space."""

    analysis_dir = "model_analysis"
    stats_fn = "holdout_outputs_01SD.pkl"

    # Subject-specific rotation matrices generated by Figure 3a.
    patient_rs = "../../dataset/patient_rs.pkl"

    A1_id = "57"
    figsize = (6, 6)
    figdpi = 300
    T_POST = 1600

    def __init__(self, model_dir, save_dir, patients_id, rand_seed, n_boot):
        self.model_dir = model_dir
        self.save_dir = save_dir
        self.patients_id = patients_id

        # Retain the common figure-class constructor signature.
        _ = rand_seed
        _ = n_boot

        self.A1_stats = None

    def make_figure(self):
        """Generate and save Figure 6a."""
        print("Making Figure 6a...")
        self._run_preprocessing()

        print("Stats for Figure 6a")
        print("------------------")

        fig = self._plot_figure_get_stats()
        save_figure(fig, self.save_dir, "Fig6a")
        return fig

    def _run_preprocessing(self):
        """Load the exemplar model outputs and subject rotation matrices."""
        for patient_id in self.patients_id:
            if patient_id != self.A1_id:
                continue

            stats_path = os.path.join(
                self.model_dir,
                "s{}".format(patient_id),
                self.analysis_dir,
                self.stats_fn,
            )
            with open(stats_path, "rb") as path:
                self.A1_stats = pickle.load(path)

        with open(self.patient_rs, "rb") as path:
            self.group_Rs = pickle.load(path)

        print(
            "Data successfully loaded from {}".format(
                self.patient_rs
            )
        )

    def _plot_figure_get_stats(self):
        """Assemble the exemplar E2E/G2E trajectory panel."""
        fig = plt.figure(
            constrained_layout=False,
            figsize=self.figsize,
            dpi=self.figdpi,
        )
        gs = fig.add_gridspec(7, 7)

        ax = fig.add_subplot(
            gs[0:7, 0:7],
            projection="3d",
        )

        plot_kwargs = {
            "xlim": [1, 21],
            "ylim": [-10, 2],
            "zlim": [-10, 2],
            "annotate": "global",
            "R": self.group_Rs[self.A1_id],
        }

        self._make_panel_A1(
            ax,
            self.A1_stats,
            elev=80,
            azim=-260,
            p_kwargs=plot_kwargs,
        )

        return fig

    def _make_panel_A1(
            self,
            ax,
            stats,
            elev=30,
            azim=60,
            p_kwargs=None,
            t_post=T_POST,
    ):
        """Plot E2E and G2E female-happy trajectories."""
        if p_kwargs is None:
            p_kwargs = {
                "xlim": [-20, 20],
                "ylim": [-10, 8],
                "zlim": [-10, 10],
            }

        plotter = PlotModelLatents(
            stats,
            post_on_dur=t_post,
            plot_pre_onset=False,
        )

        # E2E repeat trajectory.
        repeat_kwargs = dict(p_kwargs)
        repeat_kwargs["plot_t_posts"] = [1000]
        repeat_kwargs["line_styles"] = ["-"]
        repeat_kwargs["colors"] = [Constants.COLOR_E2E]

        plotter.plot_e2e_female_happy(
            ax,
            elev=elev,
            azim=azim,
            plot_task_centroid=False,
            **repeat_kwargs
        )

        # G2E switch trajectory.
        switch_kwargs = dict(p_kwargs)
        switch_kwargs["plot_t_posts"] = [1600]
        switch_kwargs["line_styles"] = ["--"]
        switch_kwargs["colors"] = [Constants.COLOR_E2E]

        plotter.plot_g2e_female_happy(
            ax,
            elev=elev,
            azim=azim,
            plot_task_centroid=False,
            **switch_kwargs
        )
