"""Generate Figure 7b: exemplar G2G and E2G latent trajectories."""

import os
import pickle

import matplotlib.pyplot as plt

from affective_task.utils import Constants, save_figure
from affective_task.visualization import PlotModelLatents


class Figure7B:
    """Plot exemplar G2G and E2G trajectories in the aligned UMAP space."""

    analysis_dir = "model_analysis"
    stats_fn = "holdout_outputs_01SD.pkl"

    # Subject-specific rotation matrices generated by Figure 3a.
    patient_rs = "../../dataset/patient_rs.pkl"

    example_id = "57"
    figsize = (9, 9)
    figdpi = 300
    T_POST = 1600

    def __init__(self, model_dir, save_dir, patients_id, rand_seed, n_boot):
        self.model_dir = model_dir
        self.save_dir = save_dir
        self.patients_id = patients_id

        # Retain the common figure-class constructor signature.
        _ = rand_seed
        _ = n_boot

        self.example_stats = None

    def make_figure(self):
        """Generate and save Figure 7b."""
        print("Making Figure 7b...")
        self._run_preprocessing()

        print("Stats for Figure 7b")
        print("------------------")

        fig = self._plot_figure_get_stats()
        save_figure(
            fig,
            self.save_dir,
            "Fig7b",
        )
        return fig

    def _run_preprocessing(self):
        """Load the exemplar model outputs and subject rotation matrices."""
        for patient_id in self.patients_id:
            if patient_id != self.example_id:
                continue

            stats_path = os.path.join(
                self.model_dir,
                "s{}".format(patient_id),
                self.analysis_dir,
                self.stats_fn,
            )
            with open(stats_path, "rb") as path:
                self.example_stats = pickle.load(path)

        with open(self.patient_rs, "rb") as path:
            self.group_Rs = pickle.load(path)

        print(
            "Data successfully loaded from {}".format(
                self.patient_rs
            )
        )

    def _plot_figure_get_stats(self):
        """Assemble the exemplar G2G/E2G trajectory panel."""
        fig = plt.figure(
            constrained_layout=False,
            figsize=self.figsize,
            dpi=self.figdpi,
        )
        gs = fig.add_gridspec(7, 7)

        ax = fig.add_subplot(
            gs[0:7, 0:7],
            projection="3d",
        )

        plot_kwargs = {
            "xlim": [-3, 17],
            "ylim": [-15, 12],
            "zlim": [-15, 3],
            "annotate": "global",
            "R": self.group_Rs[self.example_id],
        }

        self._make_panel_B(
            ax,
            self.example_stats,
            elev=80,
            azim=120,
            plot_kwargs=plot_kwargs,
        )

        return fig

    def _make_panel_B(
            self,
            ax,
            stats,
            elev=30,
            azim=60,
            plot_kwargs=None,
            t_post=T_POST,
    ):
        """Plot G2G and E2G female-happy trajectories."""
        if plot_kwargs is None:
            plot_kwargs = {
                "xlim": [-20, 20],
                "ylim": [-10, 8],
                "zlim": [-10, 10],
            }

        plotter = PlotModelLatents(
            stats,
            post_on_dur=t_post,
            plot_pre_onset=False,
        )

        # G2G repeat trajectory.
        repeat_kwargs = dict(plot_kwargs)
        repeat_kwargs["plot_t_posts"] = [1200]
        repeat_kwargs["line_styles"] = ["-"]
        repeat_kwargs["colors"] = [Constants.COLOR_G2G]

        plotter.plot_g2g_female_happy(
            ax,
            elev=elev,
            azim=azim,
            plot_task_centroid=False,
            **repeat_kwargs
        )

        # E2G switch trajectory.
        switch_kwargs = dict(plot_kwargs)
        switch_kwargs["plot_t_posts"] = [1200]
        switch_kwargs["line_styles"] = ["--"]
        switch_kwargs["colors"] = [Constants.COLOR_G2G]

        plotter.plot_e2g_female_happy(
            ax,
            elev=elev,
            azim=azim,
            plot_task_centroid=False,
            **switch_kwargs
        )
